apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubearch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kubearch.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
